export const errors = {
  usernameType: "username must be string",
  usernameLong: "username must be least 4 characters long",
  passwordType: "password must be string",
  passwordLong: "password must be least 6 characters long",
  usernameExists: "username already exists",
  usernameNotExists: "username does not exist",
  passwordInvalid: "password is invalid",
  nameType: "name must be string",
  nameRequired: "name is required",
  lastnameType: "lastname must be string",
  lastnameRequired: "lastname is required",
  birthdateType: "birthdate must be string",
  birthdateRequired: "birthdate is required",
};
